---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: node-initializer-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: privileged-role
rules:
  - apiGroups:
      - "extensions"
    resources:
      - podsecuritypolicies
    resourceNames:
      - pks-privileged
    verbs:
      - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: node-initializer-privileged-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: privileged-role
subjects:
- kind: ServiceAccount
  name: node-initializer-sa
